services:

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: brain-tumor-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/brain_tumor.db:/app/backend/brain_tumor.db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: brain-tumor-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend